// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/remora.proto

package belugav1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommandType int32

const (
	CommandType_COMMAND_TYPE_UNSPECIFIED CommandType = 0
	CommandType_GREP                     CommandType = 1
	CommandType_AWK                      CommandType = 2
	CommandType_FIND                     CommandType = 3
	CommandType_CAT                      CommandType = 4
	CommandType_READ_FILE                CommandType = 5
	CommandType_TAIL                     CommandType = 6
	CommandType_SYSTEMCTL_STATUS         CommandType = 7
	CommandType_JOURNALCTL               CommandType = 8
)

// Enum value maps for CommandType.
var (
	CommandType_name = map[int32]string{
		0: "COMMAND_TYPE_UNSPECIFIED",
		1: "GREP",
		2: "AWK",
		3: "FIND",
		4: "CAT",
		5: "READ_FILE",
		6: "TAIL",
		7: "SYSTEMCTL_STATUS",
		8: "JOURNALCTL",
	}
	CommandType_value = map[string]int32{
		"COMMAND_TYPE_UNSPECIFIED": 0,
		"GREP":                     1,
		"AWK":                      2,
		"FIND":                     3,
		"CAT":                      4,
		"READ_FILE":                5,
		"TAIL":                     6,
		"SYSTEMCTL_STATUS":         7,
		"JOURNALCTL":               8,
	}
)

func (x CommandType) Enum() *CommandType {
	p := new(CommandType)
	*p = x
	return p
}

func (x CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_remora_proto_enumTypes[0].Descriptor()
}

func (CommandType) Type() protoreflect.EnumType {
	return &file_proto_remora_proto_enumTypes[0]
}

func (x CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandType.Descriptor instead.
func (CommandType) EnumDescriptor() ([]byte, []int) {
	return file_proto_remora_proto_rawDescGZIP(), []int{0}
}

// Sent FROM remota TO beluga.
type RemotaMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*RemotaMessage_Heartbeat
	//	*RemotaMessage_CommandOutput
	//	*RemotaMessage_DirectoryChunk
	//	*RemotaMessage_Registration
	Payload       isRemotaMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemotaMessage) Reset() {
	*x = RemotaMessage{}
	mi := &file_proto_remora_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemotaMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemotaMessage) ProtoMessage() {}

func (x *RemotaMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_remora_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemotaMessage.ProtoReflect.Descriptor instead.
func (*RemotaMessage) Descriptor() ([]byte, []int) {
	return file_proto_remora_proto_rawDescGZIP(), []int{0}
}

func (x *RemotaMessage) GetPayload() isRemotaMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *RemotaMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*RemotaMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *RemotaMessage) GetCommandOutput() *CommandOutput {
	if x != nil {
		if x, ok := x.Payload.(*RemotaMessage_CommandOutput); ok {
			return x.CommandOutput
		}
	}
	return nil
}

func (x *RemotaMessage) GetDirectoryChunk() *DirectoryChunk {
	if x != nil {
		if x, ok := x.Payload.(*RemotaMessage_DirectoryChunk); ok {
			return x.DirectoryChunk
		}
	}
	return nil
}

func (x *RemotaMessage) GetRegistration() *Registration {
	if x != nil {
		if x, ok := x.Payload.(*RemotaMessage_Registration); ok {
			return x.Registration
		}
	}
	return nil
}

type isRemotaMessage_Payload interface {
	isRemotaMessage_Payload()
}

type RemotaMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,1,opt,name=heartbeat,proto3,oneof"`
}

type RemotaMessage_CommandOutput struct {
	CommandOutput *CommandOutput `protobuf:"bytes,2,opt,name=command_output,json=commandOutput,proto3,oneof"`
}

type RemotaMessage_DirectoryChunk struct {
	DirectoryChunk *DirectoryChunk `protobuf:"bytes,3,opt,name=directory_chunk,json=directoryChunk,proto3,oneof"`
}

type RemotaMessage_Registration struct {
	Registration *Registration `protobuf:"bytes,4,opt,name=registration,proto3,oneof"`
}

func (*RemotaMessage_Heartbeat) isRemotaMessage_Payload() {}

func (*RemotaMessage_CommandOutput) isRemotaMessage_Payload() {}

func (*RemotaMessage_DirectoryChunk) isRemotaMessage_Payload() {}

func (*RemotaMessage_Registration) isRemotaMessage_Payload() {}

// Sent FROM beluga TO remota.
type BelugaCommand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*BelugaCommand_ExecuteCommand
	//	*BelugaCommand_SyncDirectory
	Payload       isBelugaCommand_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BelugaCommand) Reset() {
	*x = BelugaCommand{}
	mi := &file_proto_remora_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BelugaCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BelugaCommand) ProtoMessage() {}

func (x *BelugaCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_remora_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BelugaCommand.ProtoReflect.Descriptor instead.
func (*BelugaCommand) Descriptor() ([]byte, []int) {
	return file_proto_remora_proto_rawDescGZIP(), []int{1}
}

func (x *BelugaCommand) GetPayload() isBelugaCommand_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *BelugaCommand) GetExecuteCommand() *ExecuteCommandRequest {
	if x != nil {
		if x, ok := x.Payload.(*BelugaCommand_ExecuteCommand); ok {
			return x.ExecuteCommand
		}
	}
	return nil
}

func (x *BelugaCommand) GetSyncDirectory() *SyncDirectoryRequest {
	if x != nil {
		if x, ok := x.Payload.(*BelugaCommand_SyncDirectory); ok {
			return x.SyncDirectory
		}
	}
	return nil
}

type isBelugaCommand_Payload interface {
	isBelugaCommand_Payload()
}

type BelugaCommand_ExecuteCommand struct {
	ExecuteCommand *ExecuteCommandRequest `protobuf:"bytes,1,opt,name=execute_command,json=executeCommand,proto3,oneof"`
}

type BelugaCommand_SyncDirectory struct {
	SyncDirectory *SyncDirectoryRequest `protobuf:"bytes,2,opt,name=sync_directory,json=syncDirectory,proto3,oneof"`
}

func (*BelugaCommand_ExecuteCommand) isBelugaCommand_Payload() {}

func (*BelugaCommand_SyncDirectory) isBelugaCommand_Payload() {}

type Registration struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	HostId             string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"` // unique identifier for this remote host
	Hostname           string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	AllowedDirectories []string               `protobuf:"bytes,3,rep,name=allowed_directories,json=allowedDirectories,proto3" json:"allowed_directories,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Registration) Reset() {
	*x = Registration{}
	mi := &file_proto_remora_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Registration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Registration) ProtoMessage() {}

func (x *Registration) ProtoReflect() protoreflect.Message {
	mi := &file_proto_remora_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Registration.ProtoReflect.Descriptor instead.
func (*Registration) Descriptor() ([]byte, []int) {
	return file_proto_remora_proto_rawDescGZIP(), []int{2}
}

func (x *Registration) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *Registration) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Registration) GetAllowedDirectories() []string {
	if x != nil {
		return x.AllowedDirectories
	}
	return nil
}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimestampMs   int64                  `protobuf:"varint,1,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_proto_remora_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_remora_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_proto_remora_proto_rawDescGZIP(), []int{3}
}

func (x *Heartbeat) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

type ExecuteCommandRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RequestId      string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Command        CommandType            `protobuf:"varint,2,opt,name=command,proto3,enum=beluga.v1.CommandType" json:"command,omitempty"`
	Args           []string               `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	WorkingDir     string                 `protobuf:"bytes,4,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"` // must be within allowed directories
	TimeoutSeconds int32                  `protobuf:"varint,5,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecuteCommandRequest) Reset() {
	*x = ExecuteCommandRequest{}
	mi := &file_proto_remora_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteCommandRequest) ProtoMessage() {}

func (x *ExecuteCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_remora_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteCommandRequest.ProtoReflect.Descriptor instead.
func (*ExecuteCommandRequest) Descriptor() ([]byte, []int) {
	return file_proto_remora_proto_rawDescGZIP(), []int{4}
}

func (x *ExecuteCommandRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ExecuteCommandRequest) GetCommand() CommandType {
	if x != nil {
		return x.Command
	}
	return CommandType_COMMAND_TYPE_UNSPECIFIED
}

func (x *ExecuteCommandRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ExecuteCommandRequest) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

func (x *ExecuteCommandRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type ExecuteCommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ExitCode      int32                  `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Stdout        string                 `protobuf:"bytes,3,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        string                 `protobuf:"bytes,4,opt,name=stderr,proto3" json:"stderr,omitempty"`
	Timeout       bool                   `protobuf:"varint,5,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteCommandResponse) Reset() {
	*x = ExecuteCommandResponse{}
	mi := &file_proto_remora_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteCommandResponse) ProtoMessage() {}

func (x *ExecuteCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_remora_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteCommandResponse.ProtoReflect.Descriptor instead.
func (*ExecuteCommandResponse) Descriptor() ([]byte, []int) {
	return file_proto_remora_proto_rawDescGZIP(), []int{5}
}

func (x *ExecuteCommandResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ExecuteCommandResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ExecuteCommandResponse) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *ExecuteCommandResponse) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *ExecuteCommandResponse) GetTimeout() bool {
	if x != nil {
		return x.Timeout
	}
	return false
}

type CommandOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // matches ExecuteCommandRequest.request_id
	ExitCode      int32                  `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Stdout        string                 `protobuf:"bytes,3,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        string                 `protobuf:"bytes,4,opt,name=stderr,proto3" json:"stderr,omitempty"`
	Timeout       bool                   `protobuf:"varint,5,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandOutput) Reset() {
	*x = CommandOutput{}
	mi := &file_proto_remora_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandOutput) ProtoMessage() {}

func (x *CommandOutput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_remora_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandOutput.ProtoReflect.Descriptor instead.
func (*CommandOutput) Descriptor() ([]byte, []int) {
	return file_proto_remora_proto_rawDescGZIP(), []int{6}
}

func (x *CommandOutput) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CommandOutput) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *CommandOutput) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *CommandOutput) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *CommandOutput) GetTimeout() bool {
	if x != nil {
		return x.Timeout
	}
	return false
}

type SyncDirectoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Directory     string                 `protobuf:"bytes,2,opt,name=directory,proto3" json:"directory,omitempty"` // must be within allowed directories
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncDirectoryRequest) Reset() {
	*x = SyncDirectoryRequest{}
	mi := &file_proto_remora_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncDirectoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncDirectoryRequest) ProtoMessage() {}

func (x *SyncDirectoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_remora_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncDirectoryRequest.ProtoReflect.Descriptor instead.
func (*SyncDirectoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_remora_proto_rawDescGZIP(), []int{7}
}

func (x *SyncDirectoryRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SyncDirectoryRequest) GetDirectory() string {
	if x != nil {
		return x.Directory
	}
	return ""
}

type SyncDirectoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Files         []*FileInfo            `protobuf:"bytes,2,rep,name=files,proto3" json:"files,omitempty"`
	TarData       []byte                 `protobuf:"bytes,3,opt,name=tar_data,json=tarData,proto3" json:"tar_data,omitempty"` // tar archive of the directory
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncDirectoryResponse) Reset() {
	*x = SyncDirectoryResponse{}
	mi := &file_proto_remora_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncDirectoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncDirectoryResponse) ProtoMessage() {}

func (x *SyncDirectoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_remora_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncDirectoryResponse.ProtoReflect.Descriptor instead.
func (*SyncDirectoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_remora_proto_rawDescGZIP(), []int{8}
}

func (x *SyncDirectoryResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SyncDirectoryResponse) GetFiles() []*FileInfo {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *SyncDirectoryResponse) GetTarData() []byte {
	if x != nil {
		return x.TarData
	}
	return nil
}

type DirectoryChunk struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Types that are valid to be assigned to Data:
	//
	//	*DirectoryChunk_FileInfo
	//	*DirectoryChunk_Chunk
	//	*DirectoryChunk_Done
	Data          isDirectoryChunk_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirectoryChunk) Reset() {
	*x = DirectoryChunk{}
	mi := &file_proto_remora_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectoryChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectoryChunk) ProtoMessage() {}

func (x *DirectoryChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_remora_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectoryChunk.ProtoReflect.Descriptor instead.
func (*DirectoryChunk) Descriptor() ([]byte, []int) {
	return file_proto_remora_proto_rawDescGZIP(), []int{9}
}

func (x *DirectoryChunk) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *DirectoryChunk) GetData() isDirectoryChunk_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *DirectoryChunk) GetFileInfo() *FileInfo {
	if x != nil {
		if x, ok := x.Data.(*DirectoryChunk_FileInfo); ok {
			return x.FileInfo
		}
	}
	return nil
}

func (x *DirectoryChunk) GetChunk() []byte {
	if x != nil {
		if x, ok := x.Data.(*DirectoryChunk_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

func (x *DirectoryChunk) GetDone() bool {
	if x != nil {
		if x, ok := x.Data.(*DirectoryChunk_Done); ok {
			return x.Done
		}
	}
	return false
}

type isDirectoryChunk_Data interface {
	isDirectoryChunk_Data()
}

type DirectoryChunk_FileInfo struct {
	FileInfo *FileInfo `protobuf:"bytes,2,opt,name=file_info,json=fileInfo,proto3,oneof"`
}

type DirectoryChunk_Chunk struct {
	Chunk []byte `protobuf:"bytes,3,opt,name=chunk,proto3,oneof"` // chunk of tar data
}

type DirectoryChunk_Done struct {
	Done bool `protobuf:"varint,4,opt,name=done,proto3,oneof"` // signals end of transfer
}

func (*DirectoryChunk_FileInfo) isDirectoryChunk_Data() {}

func (*DirectoryChunk_Chunk) isDirectoryChunk_Data() {}

func (*DirectoryChunk_Done) isDirectoryChunk_Data() {}

type FileInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Path           string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Size           int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	ChecksumSha256 string                 `protobuf:"bytes,3,opt,name=checksum_sha256,json=checksumSha256,proto3" json:"checksum_sha256,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	mi := &file_proto_remora_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_remora_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_proto_remora_proto_rawDescGZIP(), []int{10}
}

func (x *FileInfo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileInfo) GetChecksumSha256() string {
	if x != nil {
		return x.ChecksumSha256
	}
	return ""
}

// Sent FROM remote extension TO beluga.
type ExtensionMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ExtensionMessage_Registration
	//	*ExtensionMessage_ToolResult
	Payload       isExtensionMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtensionMessage) Reset() {
	*x = ExtensionMessage{}
	mi := &file_proto_remora_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtensionMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtensionMessage) ProtoMessage() {}

func (x *ExtensionMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_remora_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtensionMessage.ProtoReflect.Descriptor instead.
func (*ExtensionMessage) Descriptor() ([]byte, []int) {
	return file_proto_remora_proto_rawDescGZIP(), []int{11}
}

func (x *ExtensionMessage) GetPayload() isExtensionMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ExtensionMessage) GetRegistration() *ExtensionRegistration {
	if x != nil {
		if x, ok := x.Payload.(*ExtensionMessage_Registration); ok {
			return x.Registration
		}
	}
	return nil
}

func (x *ExtensionMessage) GetToolResult() *ToolResult {
	if x != nil {
		if x, ok := x.Payload.(*ExtensionMessage_ToolResult); ok {
			return x.ToolResult
		}
	}
	return nil
}

type isExtensionMessage_Payload interface {
	isExtensionMessage_Payload()
}

type ExtensionMessage_Registration struct {
	Registration *ExtensionRegistration `protobuf:"bytes,1,opt,name=registration,proto3,oneof"`
}

type ExtensionMessage_ToolResult struct {
	ToolResult *ToolResult `protobuf:"bytes,2,opt,name=tool_result,json=toolResult,proto3,oneof"`
}

func (*ExtensionMessage_Registration) isExtensionMessage_Payload() {}

func (*ExtensionMessage_ToolResult) isExtensionMessage_Payload() {}

// Sent FROM beluga TO remote extension.
type HostRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*HostRequest_ExecuteTool
	Payload       isHostRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostRequest) Reset() {
	*x = HostRequest{}
	mi := &file_proto_remora_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostRequest) ProtoMessage() {}

func (x *HostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_remora_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostRequest.ProtoReflect.Descriptor instead.
func (*HostRequest) Descriptor() ([]byte, []int) {
	return file_proto_remora_proto_rawDescGZIP(), []int{12}
}

func (x *HostRequest) GetPayload() isHostRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *HostRequest) GetExecuteTool() *ExecuteTool {
	if x != nil {
		if x, ok := x.Payload.(*HostRequest_ExecuteTool); ok {
			return x.ExecuteTool
		}
	}
	return nil
}

type isHostRequest_Payload interface {
	isHostRequest_Payload()
}

type HostRequest_ExecuteTool struct {
	ExecuteTool *ExecuteTool `protobuf:"bytes,1,opt,name=execute_tool,json=executeTool,proto3,oneof"`
}

func (*HostRequest_ExecuteTool) isHostRequest_Payload() {}

// Remote extension registration.
type ExtensionRegistration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExtensionName string                 `protobuf:"bytes,1,opt,name=extension_name,json=extensionName,proto3" json:"extension_name,omitempty"`
	Tools         []*ToolDefinition      `protobuf:"bytes,2,rep,name=tools,proto3" json:"tools,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtensionRegistration) Reset() {
	*x = ExtensionRegistration{}
	mi := &file_proto_remora_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtensionRegistration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtensionRegistration) ProtoMessage() {}

func (x *ExtensionRegistration) ProtoReflect() protoreflect.Message {
	mi := &file_proto_remora_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtensionRegistration.ProtoReflect.Descriptor instead.
func (*ExtensionRegistration) Descriptor() ([]byte, []int) {
	return file_proto_remora_proto_rawDescGZIP(), []int{13}
}

func (x *ExtensionRegistration) GetExtensionName() string {
	if x != nil {
		return x.ExtensionName
	}
	return ""
}

func (x *ExtensionRegistration) GetTools() []*ToolDefinition {
	if x != nil {
		return x.Tools
	}
	return nil
}

// Tool definition from a remote extension.
type ToolDefinition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Parameters    string                 `protobuf:"bytes,3,opt,name=parameters,proto3" json:"parameters,omitempty"` // JSON Schema as string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolDefinition) Reset() {
	*x = ToolDefinition{}
	mi := &file_proto_remora_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolDefinition) ProtoMessage() {}

func (x *ToolDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_proto_remora_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolDefinition.ProtoReflect.Descriptor instead.
func (*ToolDefinition) Descriptor() ([]byte, []int) {
	return file_proto_remora_proto_rawDescGZIP(), []int{14}
}

func (x *ToolDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolDefinition) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ToolDefinition) GetParameters() string {
	if x != nil {
		return x.Parameters
	}
	return ""
}

// Beluga asks the remote extension to execute a tool.
type ExecuteTool struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	ToolName      string                 `protobuf:"bytes,2,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	Arguments     string                 `protobuf:"bytes,3,opt,name=arguments,proto3" json:"arguments,omitempty"` // JSON args as string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteTool) Reset() {
	*x = ExecuteTool{}
	mi := &file_proto_remora_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteTool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteTool) ProtoMessage() {}

func (x *ExecuteTool) ProtoReflect() protoreflect.Message {
	mi := &file_proto_remora_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteTool.ProtoReflect.Descriptor instead.
func (*ExecuteTool) Descriptor() ([]byte, []int) {
	return file_proto_remora_proto_rawDescGZIP(), []int{15}
}

func (x *ExecuteTool) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *ExecuteTool) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ExecuteTool) GetArguments() string {
	if x != nil {
		return x.Arguments
	}
	return ""
}

// Remote extension returns the tool result.
type ToolResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	Output        string                 `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	IsError       bool                   `protobuf:"varint,3,opt,name=is_error,json=isError,proto3" json:"is_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolResult) Reset() {
	*x = ToolResult{}
	mi := &file_proto_remora_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolResult) ProtoMessage() {}

func (x *ToolResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_remora_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolResult.ProtoReflect.Descriptor instead.
func (*ToolResult) Descriptor() ([]byte, []int) {
	return file_proto_remora_proto_rawDescGZIP(), []int{16}
}

func (x *ToolResult) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *ToolResult) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *ToolResult) GetIsError() bool {
	if x != nil {
		return x.IsError
	}
	return false
}

var File_proto_remora_proto protoreflect.FileDescriptor

const file_proto_remora_proto_rawDesc = "" +
	"\n" +
	"\x12proto/remora.proto\x12\tbeluga.v1\"\x98\x02\n" +
	"\rRemotaMessage\x124\n" +
	"\theartbeat\x18\x01 \x01(\v2\x14.beluga.v1.HeartbeatH\x00R\theartbeat\x12A\n" +
	"\x0ecommand_output\x18\x02 \x01(\v2\x18.beluga.v1.CommandOutputH\x00R\rcommandOutput\x12D\n" +
	"\x0fdirectory_chunk\x18\x03 \x01(\v2\x19.beluga.v1.DirectoryChunkH\x00R\x0edirectoryChunk\x12=\n" +
	"\fregistration\x18\x04 \x01(\v2\x17.beluga.v1.RegistrationH\x00R\fregistrationB\t\n" +
	"\apayload\"\xb1\x01\n" +
	"\rBelugaCommand\x12K\n" +
	"\x0fexecute_command\x18\x01 \x01(\v2 .beluga.v1.ExecuteCommandRequestH\x00R\x0eexecuteCommand\x12H\n" +
	"\x0esync_directory\x18\x02 \x01(\v2\x1f.beluga.v1.SyncDirectoryRequestH\x00R\rsyncDirectoryB\t\n" +
	"\apayload\"t\n" +
	"\fRegistration\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12/\n" +
	"\x13allowed_directories\x18\x03 \x03(\tR\x12allowedDirectories\".\n" +
	"\tHeartbeat\x12!\n" +
	"\ftimestamp_ms\x18\x01 \x01(\x03R\vtimestampMs\"\xc6\x01\n" +
	"\x15ExecuteCommandRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x120\n" +
	"\acommand\x18\x02 \x01(\x0e2\x16.beluga.v1.CommandTypeR\acommand\x12\x12\n" +
	"\x04args\x18\x03 \x03(\tR\x04args\x12\x1f\n" +
	"\vworking_dir\x18\x04 \x01(\tR\n" +
	"workingDir\x12'\n" +
	"\x0ftimeout_seconds\x18\x05 \x01(\x05R\x0etimeoutSeconds\"\x9e\x01\n" +
	"\x16ExecuteCommandResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1b\n" +
	"\texit_code\x18\x02 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06stdout\x18\x03 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x04 \x01(\tR\x06stderr\x12\x18\n" +
	"\atimeout\x18\x05 \x01(\bR\atimeout\"\x95\x01\n" +
	"\rCommandOutput\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1b\n" +
	"\texit_code\x18\x02 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06stdout\x18\x03 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x04 \x01(\tR\x06stderr\x12\x18\n" +
	"\atimeout\x18\x05 \x01(\bR\atimeout\"S\n" +
	"\x14SyncDirectoryRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1c\n" +
	"\tdirectory\x18\x02 \x01(\tR\tdirectory\"|\n" +
	"\x15SyncDirectoryResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12)\n" +
	"\x05files\x18\x02 \x03(\v2\x13.beluga.v1.FileInfoR\x05files\x12\x19\n" +
	"\btar_data\x18\x03 \x01(\fR\atarData\"\x99\x01\n" +
	"\x0eDirectoryChunk\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x122\n" +
	"\tfile_info\x18\x02 \x01(\v2\x13.beluga.v1.FileInfoH\x00R\bfileInfo\x12\x16\n" +
	"\x05chunk\x18\x03 \x01(\fH\x00R\x05chunk\x12\x14\n" +
	"\x04done\x18\x04 \x01(\bH\x00R\x04doneB\x06\n" +
	"\x04data\"[\n" +
	"\bFileInfo\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12'\n" +
	"\x0fchecksum_sha256\x18\x03 \x01(\tR\x0echecksumSha256\"\x9f\x01\n" +
	"\x10ExtensionMessage\x12F\n" +
	"\fregistration\x18\x01 \x01(\v2 .beluga.v1.ExtensionRegistrationH\x00R\fregistration\x128\n" +
	"\vtool_result\x18\x02 \x01(\v2\x15.beluga.v1.ToolResultH\x00R\n" +
	"toolResultB\t\n" +
	"\apayload\"U\n" +
	"\vHostRequest\x12;\n" +
	"\fexecute_tool\x18\x01 \x01(\v2\x16.beluga.v1.ExecuteToolH\x00R\vexecuteToolB\t\n" +
	"\apayload\"o\n" +
	"\x15ExtensionRegistration\x12%\n" +
	"\x0eextension_name\x18\x01 \x01(\tR\rextensionName\x12/\n" +
	"\x05tools\x18\x02 \x03(\v2\x19.beluga.v1.ToolDefinitionR\x05tools\"f\n" +
	"\x0eToolDefinition\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"parameters\x18\x03 \x01(\tR\n" +
	"parameters\"a\n" +
	"\vExecuteTool\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x1b\n" +
	"\ttool_name\x18\x02 \x01(\tR\btoolName\x12\x1c\n" +
	"\targuments\x18\x03 \x01(\tR\targuments\"X\n" +
	"\n" +
	"ToolResult\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x16\n" +
	"\x06output\x18\x02 \x01(\tR\x06output\x12\x19\n" +
	"\bis_error\x18\x03 \x01(\bR\aisError*\x90\x01\n" +
	"\vCommandType\x12\x1c\n" +
	"\x18COMMAND_TYPE_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04GREP\x10\x01\x12\a\n" +
	"\x03AWK\x10\x02\x12\b\n" +
	"\x04FIND\x10\x03\x12\a\n" +
	"\x03CAT\x10\x04\x12\r\n" +
	"\tREAD_FILE\x10\x05\x12\b\n" +
	"\x04TAIL\x10\x06\x12\x14\n" +
	"\x10SYSTEMCTL_STATUS\x10\a\x12\x0e\n" +
	"\n" +
	"JOURNALCTL\x10\b2\xfd\x01\n" +
	"\rRemoraService\x12A\n" +
	"\aConnect\x12\x18.beluga.v1.RemotaMessage\x1a\x18.beluga.v1.BelugaCommand(\x010\x01\x12U\n" +
	"\x0eExecuteCommand\x12 .beluga.v1.ExecuteCommandRequest\x1a!.beluga.v1.ExecuteCommandResponse\x12R\n" +
	"\rSyncDirectory\x12\x1f.beluga.v1.SyncDirectoryRequest\x1a .beluga.v1.SyncDirectoryResponse2Z\n" +
	"\x14ExtensionHostService\x12B\n" +
	"\aConnect\x12\x1b.beluga.v1.ExtensionMessage\x1a\x16.beluga.v1.HostRequest(\x010\x01B3Z1github.com/collinpfeifer/beluga/internal/belugav1b\x06proto3"

var (
	file_proto_remora_proto_rawDescOnce sync.Once
	file_proto_remora_proto_rawDescData []byte
)

func file_proto_remora_proto_rawDescGZIP() []byte {
	file_proto_remora_proto_rawDescOnce.Do(func() {
		file_proto_remora_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_remora_proto_rawDesc), len(file_proto_remora_proto_rawDesc)))
	})
	return file_proto_remora_proto_rawDescData
}

var file_proto_remora_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_remora_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_proto_remora_proto_goTypes = []any{
	(CommandType)(0),               // 0: beluga.v1.CommandType
	(*RemotaMessage)(nil),          // 1: beluga.v1.RemotaMessage
	(*BelugaCommand)(nil),          // 2: beluga.v1.BelugaCommand
	(*Registration)(nil),           // 3: beluga.v1.Registration
	(*Heartbeat)(nil),              // 4: beluga.v1.Heartbeat
	(*ExecuteCommandRequest)(nil),  // 5: beluga.v1.ExecuteCommandRequest
	(*ExecuteCommandResponse)(nil), // 6: beluga.v1.ExecuteCommandResponse
	(*CommandOutput)(nil),          // 7: beluga.v1.CommandOutput
	(*SyncDirectoryRequest)(nil),   // 8: beluga.v1.SyncDirectoryRequest
	(*SyncDirectoryResponse)(nil),  // 9: beluga.v1.SyncDirectoryResponse
	(*DirectoryChunk)(nil),         // 10: beluga.v1.DirectoryChunk
	(*FileInfo)(nil),               // 11: beluga.v1.FileInfo
	(*ExtensionMessage)(nil),       // 12: beluga.v1.ExtensionMessage
	(*HostRequest)(nil),            // 13: beluga.v1.HostRequest
	(*ExtensionRegistration)(nil),  // 14: beluga.v1.ExtensionRegistration
	(*ToolDefinition)(nil),         // 15: beluga.v1.ToolDefinition
	(*ExecuteTool)(nil),            // 16: beluga.v1.ExecuteTool
	(*ToolResult)(nil),             // 17: beluga.v1.ToolResult
}
var file_proto_remora_proto_depIdxs = []int32{
	4,  // 0: beluga.v1.RemotaMessage.heartbeat:type_name -> beluga.v1.Heartbeat
	7,  // 1: beluga.v1.RemotaMessage.command_output:type_name -> beluga.v1.CommandOutput
	10, // 2: beluga.v1.RemotaMessage.directory_chunk:type_name -> beluga.v1.DirectoryChunk
	3,  // 3: beluga.v1.RemotaMessage.registration:type_name -> beluga.v1.Registration
	5,  // 4: beluga.v1.BelugaCommand.execute_command:type_name -> beluga.v1.ExecuteCommandRequest
	8,  // 5: beluga.v1.BelugaCommand.sync_directory:type_name -> beluga.v1.SyncDirectoryRequest
	0,  // 6: beluga.v1.ExecuteCommandRequest.command:type_name -> beluga.v1.CommandType
	11, // 7: beluga.v1.SyncDirectoryResponse.files:type_name -> beluga.v1.FileInfo
	11, // 8: beluga.v1.DirectoryChunk.file_info:type_name -> beluga.v1.FileInfo
	14, // 9: beluga.v1.ExtensionMessage.registration:type_name -> beluga.v1.ExtensionRegistration
	17, // 10: beluga.v1.ExtensionMessage.tool_result:type_name -> beluga.v1.ToolResult
	16, // 11: beluga.v1.HostRequest.execute_tool:type_name -> beluga.v1.ExecuteTool
	15, // 12: beluga.v1.ExtensionRegistration.tools:type_name -> beluga.v1.ToolDefinition
	1,  // 13: beluga.v1.RemoraService.Connect:input_type -> beluga.v1.RemotaMessage
	5,  // 14: beluga.v1.RemoraService.ExecuteCommand:input_type -> beluga.v1.ExecuteCommandRequest
	8,  // 15: beluga.v1.RemoraService.SyncDirectory:input_type -> beluga.v1.SyncDirectoryRequest
	12, // 16: beluga.v1.ExtensionHostService.Connect:input_type -> beluga.v1.ExtensionMessage
	2,  // 17: beluga.v1.RemoraService.Connect:output_type -> beluga.v1.BelugaCommand
	6,  // 18: beluga.v1.RemoraService.ExecuteCommand:output_type -> beluga.v1.ExecuteCommandResponse
	9,  // 19: beluga.v1.RemoraService.SyncDirectory:output_type -> beluga.v1.SyncDirectoryResponse
	13, // 20: beluga.v1.ExtensionHostService.Connect:output_type -> beluga.v1.HostRequest
	17, // [17:21] is the sub-list for method output_type
	13, // [13:17] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_proto_remora_proto_init() }
func file_proto_remora_proto_init() {
	if File_proto_remora_proto != nil {
		return
	}
	file_proto_remora_proto_msgTypes[0].OneofWrappers = []any{
		(*RemotaMessage_Heartbeat)(nil),
		(*RemotaMessage_CommandOutput)(nil),
		(*RemotaMessage_DirectoryChunk)(nil),
		(*RemotaMessage_Registration)(nil),
	}
	file_proto_remora_proto_msgTypes[1].OneofWrappers = []any{
		(*BelugaCommand_ExecuteCommand)(nil),
		(*BelugaCommand_SyncDirectory)(nil),
	}
	file_proto_remora_proto_msgTypes[9].OneofWrappers = []any{
		(*DirectoryChunk_FileInfo)(nil),
		(*DirectoryChunk_Chunk)(nil),
		(*DirectoryChunk_Done)(nil),
	}
	file_proto_remora_proto_msgTypes[11].OneofWrappers = []any{
		(*ExtensionMessage_Registration)(nil),
		(*ExtensionMessage_ToolResult)(nil),
	}
	file_proto_remora_proto_msgTypes[12].OneofWrappers = []any{
		(*HostRequest_ExecuteTool)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_remora_proto_rawDesc), len(file_proto_remora_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_remora_proto_goTypes,
		DependencyIndexes: file_proto_remora_proto_depIdxs,
		EnumInfos:         file_proto_remora_proto_enumTypes,
		MessageInfos:      file_proto_remora_proto_msgTypes,
	}.Build()
	File_proto_remora_proto = out.File
	file_proto_remora_proto_goTypes = nil
	file_proto_remora_proto_depIdxs = nil
}
