// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/remora.proto

package belugav1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RemoraService_Connect_FullMethodName        = "/beluga.v1.RemoraService/Connect"
	RemoraService_ExecuteCommand_FullMethodName = "/beluga.v1.RemoraService/ExecuteCommand"
	RemoraService_SyncDirectory_FullMethodName  = "/beluga.v1.RemoraService/SyncDirectory"
)

// RemoraServiceClient is the client API for RemoraService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RemoraServiceClient interface {
	// Bidirectional stream: remora connects and keeps the stream alive.
	// Beluga sends commands through the stream; the remora responds
	// with output, heartbeats, and directory sync data.
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RemotaMessage, BelugaCommand], error)
	// Unary fallback: execute a single command on the remote host.
	ExecuteCommand(ctx context.Context, in *ExecuteCommandRequest, opts ...grpc.CallOption) (*ExecuteCommandResponse, error)
	// Unary: trigger a directory sync from the remote host.
	SyncDirectory(ctx context.Context, in *SyncDirectoryRequest, opts ...grpc.CallOption) (*SyncDirectoryResponse, error)
}

type remoraServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRemoraServiceClient(cc grpc.ClientConnInterface) RemoraServiceClient {
	return &remoraServiceClient{cc}
}

func (c *remoraServiceClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RemotaMessage, BelugaCommand], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RemoraService_ServiceDesc.Streams[0], RemoraService_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RemotaMessage, BelugaCommand]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RemoraService_ConnectClient = grpc.BidiStreamingClient[RemotaMessage, BelugaCommand]

func (c *remoraServiceClient) ExecuteCommand(ctx context.Context, in *ExecuteCommandRequest, opts ...grpc.CallOption) (*ExecuteCommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteCommandResponse)
	err := c.cc.Invoke(ctx, RemoraService_ExecuteCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remoraServiceClient) SyncDirectory(ctx context.Context, in *SyncDirectoryRequest, opts ...grpc.CallOption) (*SyncDirectoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncDirectoryResponse)
	err := c.cc.Invoke(ctx, RemoraService_SyncDirectory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RemoraServiceServer is the server API for RemoraService service.
// All implementations must embed UnimplementedRemoraServiceServer
// for forward compatibility.
type RemoraServiceServer interface {
	// Bidirectional stream: remora connects and keeps the stream alive.
	// Beluga sends commands through the stream; the remora responds
	// with output, heartbeats, and directory sync data.
	Connect(grpc.BidiStreamingServer[RemotaMessage, BelugaCommand]) error
	// Unary fallback: execute a single command on the remote host.
	ExecuteCommand(context.Context, *ExecuteCommandRequest) (*ExecuteCommandResponse, error)
	// Unary: trigger a directory sync from the remote host.
	SyncDirectory(context.Context, *SyncDirectoryRequest) (*SyncDirectoryResponse, error)
	mustEmbedUnimplementedRemoraServiceServer()
}

// UnimplementedRemoraServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRemoraServiceServer struct{}

func (UnimplementedRemoraServiceServer) Connect(grpc.BidiStreamingServer[RemotaMessage, BelugaCommand]) error {
	return status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedRemoraServiceServer) ExecuteCommand(context.Context, *ExecuteCommandRequest) (*ExecuteCommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteCommand not implemented")
}
func (UnimplementedRemoraServiceServer) SyncDirectory(context.Context, *SyncDirectoryRequest) (*SyncDirectoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncDirectory not implemented")
}
func (UnimplementedRemoraServiceServer) mustEmbedUnimplementedRemoraServiceServer() {}
func (UnimplementedRemoraServiceServer) testEmbeddedByValue()                       {}

// UnsafeRemoraServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RemoraServiceServer will
// result in compilation errors.
type UnsafeRemoraServiceServer interface {
	mustEmbedUnimplementedRemoraServiceServer()
}

func RegisterRemoraServiceServer(s grpc.ServiceRegistrar, srv RemoraServiceServer) {
	// If the following call panics, it indicates UnimplementedRemoraServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RemoraService_ServiceDesc, srv)
}

func _RemoraService_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RemoraServiceServer).Connect(&grpc.GenericServerStream[RemotaMessage, BelugaCommand]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RemoraService_ConnectServer = grpc.BidiStreamingServer[RemotaMessage, BelugaCommand]

func _RemoraService_ExecuteCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemoraServiceServer).ExecuteCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RemoraService_ExecuteCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemoraServiceServer).ExecuteCommand(ctx, req.(*ExecuteCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RemoraService_SyncDirectory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncDirectoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemoraServiceServer).SyncDirectory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RemoraService_SyncDirectory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemoraServiceServer).SyncDirectory(ctx, req.(*SyncDirectoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RemoraService_ServiceDesc is the grpc.ServiceDesc for RemoraService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RemoraService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "beluga.v1.RemoraService",
	HandlerType: (*RemoraServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteCommand",
			Handler:    _RemoraService_ExecuteCommand_Handler,
		},
		{
			MethodName: "SyncDirectory",
			Handler:    _RemoraService_SyncDirectory_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _RemoraService_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/remora.proto",
}

const (
	ExtensionHostService_Connect_FullMethodName = "/beluga.v1.ExtensionHostService/Connect"
)

// ExtensionHostServiceClient is the client API for ExtensionHostService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExtensionHostServiceClient interface {
	// Bidirectional stream for remote extension communication.
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ExtensionMessage, HostRequest], error)
}

type extensionHostServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewExtensionHostServiceClient(cc grpc.ClientConnInterface) ExtensionHostServiceClient {
	return &extensionHostServiceClient{cc}
}

func (c *extensionHostServiceClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ExtensionMessage, HostRequest], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ExtensionHostService_ServiceDesc.Streams[0], ExtensionHostService_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExtensionMessage, HostRequest]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ExtensionHostService_ConnectClient = grpc.BidiStreamingClient[ExtensionMessage, HostRequest]

// ExtensionHostServiceServer is the server API for ExtensionHostService service.
// All implementations must embed UnimplementedExtensionHostServiceServer
// for forward compatibility.
type ExtensionHostServiceServer interface {
	// Bidirectional stream for remote extension communication.
	Connect(grpc.BidiStreamingServer[ExtensionMessage, HostRequest]) error
	mustEmbedUnimplementedExtensionHostServiceServer()
}

// UnimplementedExtensionHostServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExtensionHostServiceServer struct{}

func (UnimplementedExtensionHostServiceServer) Connect(grpc.BidiStreamingServer[ExtensionMessage, HostRequest]) error {
	return status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedExtensionHostServiceServer) mustEmbedUnimplementedExtensionHostServiceServer() {}
func (UnimplementedExtensionHostServiceServer) testEmbeddedByValue()                              {}

// UnsafeExtensionHostServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExtensionHostServiceServer will
// result in compilation errors.
type UnsafeExtensionHostServiceServer interface {
	mustEmbedUnimplementedExtensionHostServiceServer()
}

func RegisterExtensionHostServiceServer(s grpc.ServiceRegistrar, srv ExtensionHostServiceServer) {
	// If the following call panics, it indicates UnimplementedExtensionHostServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ExtensionHostService_ServiceDesc, srv)
}

func _ExtensionHostService_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ExtensionHostServiceServer).Connect(&grpc.GenericServerStream[ExtensionMessage, HostRequest]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ExtensionHostService_ConnectServer = grpc.BidiStreamingServer[ExtensionMessage, HostRequest]

// ExtensionHostService_ServiceDesc is the grpc.ServiceDesc for ExtensionHostService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExtensionHostService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "beluga.v1.ExtensionHostService",
	HandlerType: (*ExtensionHostServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _ExtensionHostService_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/remora.proto",
}
